project:
  type: website
  output-dir: docs
  resources: CNAME

website:
  description: "A Quarto blog for PyTorch."
  site-url: https://passthetorch.dev # you must change this appropriately for RSS feeds to work properly
  title: "Pass The Torch"
  favicon: favicon.ico
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/howardbaik/pass-the-torch
format:
  html:
    theme:
      - simplex
      - brand
    css: styles.css



